### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by einarf** [DalyaG/PyGraphicsGui#1]
Hello!

Is there a missing package in `requirements.txt` or a missing module?
```
Traceback (most recent call last):
  File "run_where_is_waldo.py", line 5, in <module>
    from src.window_manager import WindowManager
  File "C:\Users\efors\projects\moderngl\PyGraphicsGui\src\window_manager.py", line 6, in <module>
    from src.bounding_box import BoundingBox
  File "C:\Users\efors\projects\moderngl\PyGraphicsGui\src\bounding_box.py", line 3, in <module>
    from attr import dataclass
ModuleNotFoundError: No module named 'attr'
```

**Comment by DalyaGartzman-SiteAware** [comment]
Thanks!!!
Indeed it was missing, updated the requirements file accordingly :)

**Comment by DalyaG** [comment]
Thanks!!
Indeed it was missing...
Updated requirements to include attrs :)

**Comment by einarf** [comment]
Works 👍

**Comment by DalyaG** [comment]
Thanks for bringing this up and thanks for the validation!! :)
